# Generated by Django 2.2.7 on 2019-11-05 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('constraint_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subfield',
            fields=[
                ('subfield_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tableau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1000)),
                ('tab_citation', models.CharField(max_length=1000)),
                ('tab_constraints', models.ManyToManyField(to='otbank.Constraint')),
            ],
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition_text', models.CharField(max_length=1000)),
                ('definition_citation', models.CharField(max_length=1000)),
                ('primary', models.BooleanField(default=False)),
                ('constraint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otbank.Constraint')),
            ],
        ),
        migrations.AddField(
            model_name='constraint',
            name='subfield',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otbank.Subfield'),
        ),
    ]
